language: objective-c
install: true
osx_image: xcode8.2
xcode_workspace: SilentRunner/SilentRunner.xcworkspace
xcode_scheme: SilentRunnerEngine
branches:
  only:
  - master
  - /^\d+\.\d+\.\d+.*$/
env:
  global:
    - FRAMEWORK_NAME=SilentRunnerEngine
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - gem install cocoapods
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap
  - pod setup
script:
  - travis_retry xcodebuild -workspace SilentRunner/SilentRunner.xcworkspace  -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' -scheme SilentRunnerEngine  test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - pod lib lint --use-libraries --allow-warnings SilentRunnerEngine.podspec
  - carthage build --no-skip-current
before_deploy:
  - carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: HouseOfRisingSun/SilentRunner
    tags: true
  provider: script
  script: ./scripts/push.sh
  on:
    tags: true
