language: objective-c
install: true
branches:
  only:
  - master
script:
  - xcodebuild -workspace SilentRunner/SilentRunner.xcworkspace  -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' -scheme SilentRunnerEngine  test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
osx_image: xcode8.2