language: objective-c 
script:
	- xcodebuild -workspace SilentRunner/SilentRunner.xcworkspace  -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' -scheme SilentRunnerEngine  test