# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SilentRunner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  target 'SilentRunnerEngine' do
    inherit! :search_paths
    pod 'JSONRPCom'
    pod 'SocketRocket'
    pod 'OCMockito', '~> 4.0'
    pod 'Mantle'
    
  end

  target 'SilentRunnerEngineTests' do
    inherit! :search_paths    
  end

end

post_install do |installer|  
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|  
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'  
  end  
end  
