# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SilentRunner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SilentRunner
  pod 'JSONRPCom', :git => 'https://github.com/andrewBatutin/JSONRPCom.git'
  pod 'SocketRocket'
  pod 'OCMockito', '~> 4.0'

  target 'SilentRunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SilentRunnerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SilentRunnerEngine' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SilentRunnerEngineTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'JSONRPCom', :git => 'https://github.com/andrewBatutin/JSONRPCom.git'
    pod 'SocketRocket'
    pod 'OCMockito', '~> 4.0'
  end

end
