# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SilentRunner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SilentRunner
  pod 'JSONRPCom', :git => 'https://github.com/andrewBatutin/JSONRPCom.git'
  pod 'SocketRocket'
  pod 'OCMockito', '~> 4.0'



  target 'SilentRunnerEngine' do
    inherit! :search_paths
    # Pods for testing
    pod 'JSONRPCom', :git => 'https://github.com/andrewBatutin/JSONRPCom.git'
    pod 'SocketRocket'
    pod 'OCMockito', '~> 4.0'
    pod 'Mantle'
    pod 'MAObjCRuntime'
    pod 'ReactiveCocoa', '5.0.0-alpha.5'
  end

  target 'SilentRunnerEngineTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
